### ISSUE TITLE
Suggestion: Game! Menu music delay

### ISSUE THREAD

**Issue by davidvkimball** [Noah-C-S/SlippiMusic#2]
Great little player! I have a minor complaint, and that's when the Game! screen shows at the end of a match, the menu music immediately plays. Is it possible to give it a delay upon end of match? I tried manually delaying the timing of the menu music in Audacity which works well, except when you L+R+A+START / quit out of a match, where the delay is awkward.

**Comment by Noah-C-S** [comment]
You're right, the menu music implementation is rather imperfect for a few reasons, but the biggest one is that the program currently only watches for the "game start" and "game end" events and ignores all other information. Once it connects to the console, it plays the menu music until it receives "game start", and then plays the stage music until it receives "game end" at which point it plays the menu music again. 
The "game end" signal is sent the instant the game ends, so that's why it plays the menu music immediately. Dolphin does send other kinds of events, including one called a "menu event", and I'm going to try to figure out how to use this other information to more accurately emulate the menu music, but if I can't figure it out, a static waiting period between when it receives the "game end" event and when it starts playing the menu music could improve it. Thanks for the suggestion!

**Comment by Noah-C-S** [comment]
All right, I looked into it and while menu events are documented, the game never actually seems to send any over. However, I was able to implement this by imposing a static waiting period of two seconds before playing the menu theme on games that didn't end with LRAS.
I detect this by keeping track of player stock counts, and if more than half the players lost all of their stocks, then the program assumes that the game ended normally. Otherwise, it assumes that the game ended through LRAS. This should work in all situations for 1v1, though a particular situation in teams (LRAS when each team has 1 player left) would break it and make it think that the game ended normally. 
I implemented this and a few other things on [this commit on Dev](https://github.com/Noah-C-S/SlippiMusic/commit/0ce488bde086da45bba935a0db8699b69e5bc258), I'll add more features and test it more on multiple platforms before merging it with master and making a new release.
